sudo: false

language: rust

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

script:
  scripts/build.sh
after_success:
  scripts/publish.sh

notifications:
  email: false
