language: rust

matrix:
  include:
    - rust: stable
    - rust: beta
    - rust: nightly
    - rust: 1.31.0
    - rust: nightly
      env: CLIPPY
      script: |
          if rustup component add clippy; then
              cargo clippy
          fi

script:
  - cargo build
  - cargo test
