language: rust

matrix:
  include:
    - rust: stable
    - rust: beta
    - rust: nightly
    - rust: 1.17.0
      script: cargo check
    - rust: 1.21.0
      script:
        - cargo build
        - cargo test
    - rust: nightly
      env: CLIPPY
      script: |
          if rustup component add clippy-preview; then
              cargo clippy -- -Dclippy
          fi

script:
  - cargo build
  - cargo test
  - cargo test --features "i128"
