[package]
name = "serde_yaml"
version = "0.2.0"
authors = ["David Tolnay <dtolnay@gmail.com>"]
license = "MIT/Apache-2.0"
description = "YAML support for Serde"
repository = "https://github.com/dtolnay/serde-yaml"
documentation = "https://dtolnay.github.io/serde-yaml/"
readme = "README.md"
keywords = ["yaml", "serde"]

[dependencies]
clippy = { version = "^0.*", optional = true }
serde = "^0.7"
serde_macros = "^0.7"
yaml-rust = "^0.3"

[features]
default = ["clippy"]
