[package]
name = "serde_yaml_tests"
version = "0.0.0"
authors = ["David Tolnay <dtolnay@gmail.com>"]
publish = false

[dependencies]
serde = "0.9"
serde_yaml = { path = "../yaml" }
serde_derive = "0.9"
unindent = "0.1"

[[test]]
name = "test"
path = "tests/test.rs"
