[package]
name = "serde_yaml_tests"
version = "0.5.1"
authors = ["David Tolnay <dtolnay@gmail.com>"]

[dependencies]
serde = "0.8"
serde_yaml = { path = "../yaml" }
serde_derive = "0.8"
indoc = "*"

[[test]]
name = "test"
path = "tests/test.rs"
