[package]
name = "serde_yaml"
version = "0.2.5"
authors = ["David Tolnay <dtolnay@gmail.com>"]
license = "MIT/Apache-2.0"
description = "YAML support for Serde"
repository = "https://github.com/dtolnay/serde-yaml"
documentation = "https://dtolnay.github.io/serde-yaml/"
readme = "../README.md"
keywords = ["yaml", "serde"]

[features]
preserve_order = ["yaml-rust/preserve_order"]

[dependencies]
clippy = { version = "^0.*", optional = true }
serde = "^0.7"
yaml-rust = "^0.3.2"
